### ISSUE TITLE
Word Wrap and Spacing Defaults

### ISSUE THREAD

**Issue by bcrotty** [SublimeText/PowerShell#106]
Do we want to set defaults for word wrapping and tabs vs. spaces? I personally prefer the opposite of how it is set now. What about just not having these defaults?

**Comment by vors** [comment]
I personally prefer how it set up now. @guillermooo , what's the common practice in ST packages?

**Comment by bcrotty** [comment]
Is there a PowerShell specific reason to have either of those settings as defaults, since this will override the user preferences?

**Comment by vors** [comment]
No.

**Comment by guillermooo** [comment]
We probably should not make any call on behalf users regarding white space.

Until the PS analyzer establishes a convention, I guess we should delete the setting because it's a subjective choice.

That said, between changing the default setting and keeping it as it is, I'd rather keep it.

Anyone thinks it's a big deal deleting it?

**Comment by bcrotty** [comment]
That works for me.

**Comment by vors** [comment]
:+1:

**Comment by eugenesvk** [comment]
Would you please delete these settings as it's very annoying that my user settings are overridden and I have to have a custom exception for one language.
You can easily set your preferences in your own config files as you like, no need to force it on other users.

**Comment by bcrotty** [comment]
@vors @guillermooo I think we agreed to remove these settings so that it doesn't override user preferences. Would one of you mind changing that?
